name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [14.x, 16.x, 18.x]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    
    - run: npm run build --if-present
    
    - run: npm test
      continue-on-error: true # Esto evitará que el flujo de trabajo falle si las pruebas no pasan
    
    - name: Check test results and prevent merge if tests fail
      run: |
        if [ ${{ success() }} == 'false' ]; then
          echo "Tests failed. This pull request cannot be merged."
          exit 1
        fi
      if: failure() # Esto asegura que este paso solo se ejecute si las pruebas fallan
